export { CasesSection } from './CasesSection';
export { DiagnosticSection } from './DiagnosticSection';
export { ExpertiseSection } from './ExpertiseSection';
export { Footer } from './Footer';
export { HeroSection } from './HeroSection';
export { ServicesSection } from './ServicesSection';
export { SubscribeSection } from './SubscribeSection';
export { TestimonialsSection } from './TestimonialsSection';
export { VideoSection } from './VideoSection';
